version: '2'

services:
  mysql:
    container_name: 'mysql'
    image: 'docker.io/bitnami/mysql:5.7.32'
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=companies-manager"
      - "MYSQL_USERNAME=root"
      - "MYSQL_PASSWORD=secret"
    volumes:
      - mysqldata:/bitnami/mysql/data

  upload-api:
    container_name: 'upload-api'
    image: php:7.3-apache
    ports:
      - 3001:80
    volumes:
      - ./upload-api/:/var/www/html
      - ./config/upload-api.php.ini:/usr/local/etc/php/conf.d/upload-api.php.ini

  companies-manager:
    container_name: 'companies-manager'
    image: docker.io/bitnami/laravel:7.30.1
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=companies-manager"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=secret"
    depends_on:
      - mysql
      - upload-api
    ports:
      - 3000:3000
    volumes:
      - ./companies-manager/:/app

volumes:
  mysqldata:
